server:
  port: 8090
  servlet:
    context-path: /api

spring:
  datasource:
    # JDBC 连接相关配置
    # driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    # url: jdbc:mysql://localhost:3306/library-ms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    url: jdbc:p6spy:mysql://localhost:3306/library-ms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: libraryms
    password: 123456
    # 数据库连接池相关配置
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: LibraryManageSystem
      max-lifetime: 60000
      connection-timeout: 30000

mybatis-plus:
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型默认设置为自动递增
      id-type: AUTO
  configuration:
    # 开启自动驼峰命名规则映射
    map-underscore-to-camel-case: true