/*
 Source Server         : LibraryMS
 Source Server Type    : MySQL
 Source Server Version : 80020
 Source Host           : localhost:3306
 Source Schema         : library-ms

 Target Server Type    : MySQL
 Target Server Version : 80020
 File Encoding         : 65001
*/

SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Records of book
-- ----------------------------
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`, `book_lent`) VALUES ('共产党宣言', '马克思',  288, 5, 2);
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`, `book_lent`) VALUES ('马克思的实践辩证法思想研究', '熊文',  296, 3, 1);
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`) VALUES ('习近平用典', '人民日报',  299, 4);
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`) VALUES ('不平等经济学', '皮凯蒂',  312, 2);
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`, `book_lent`) VALUES ('现代汉语词典', '中国社科院词典编辑室语言研究所',  329, 1, 1);
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`) VALUES ('呼兰河传', '萧红',  340, 2);
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`, `book_lent`) VALUES ('流浪地球', '刘慈欣', 340, 5, 1);
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`) VALUES ('活着', '余华', 340, 3);INSERT INTO `book` (`book_name`, `book_author`, `cat_id`, `book_total`) VALUES ('我的故乡在八十年代', '周可', 353, 1);
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`, `book_lent`) VALUES ('概率论与数理统计', '沈恒范', 368, 2, 2);
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`) VALUES ('黑洞 : 不可思议的神秘宇宙之谜', '谷峰', 379, 2);
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`) VALUES ('蛋白质化学', '汪世龙', 389, 2);
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`) VALUES ('心脏超声入门', '赵维鹏', 405, 1);
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`) VALUES ('Effective Java', '布洛克', 433, 4);
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`) VALUES ('C++ Primer Plus', 'Stephen Prata', 433, 3);
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`) VALUES ('Vue.js实战', '梁灏', 433, 3);
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`) VALUES ('Spring Boot实战派', '龙中华', 433, 2);
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`) VALUES ('数据库系统概论', '王珊', 433, 5);
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`) VALUES ('微信小程序入门', '厉业崧', 422, 4);
INSERT INTO `book`(`book_name`, `book_author`, `cat_id`, `book_total`) VALUES ('无人机系统导论', '法尔斯特伦', 444, 1);

-- ----------------------------
-- Records of category
-- ----------------------------
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ( 'A', '马克思主义、列宁主义、毛泽东思想、邓小平理论', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B', '哲学、宗教', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('C', '社会科学总论', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D', '政治、法律', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('E', '军事', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F', '经济', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('G', '文化、科学、教育、体育', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H', '语言、文字', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I', '文学', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('J', '艺术', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K', '历史、地理', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('N', '自然科学总论', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O', '数理科学和化学', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P', '天文学、地球科学', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q', '生物科学', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R', '医药、卫生', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('S', '农业科学', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('T', '工业技术', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('U', '交通运输', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('V', '航空、航天', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('X', '环境科学、安全科学', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Z', '综合性图书', NULL, 0);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('A1', '马克思、恩格斯著作', 1, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('A2', '列宁著作', 1, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('A3', '斯大林著作', 1, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('A4', '毛泽东著作', 1, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('A49', '邓小平著作', 1, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('A5', '马克思、恩格斯、列宁、斯大林、毛泽东、邓小平著作汇编', 1, 1); 
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('A7', '马克思、恩格斯、列宁、斯大林、毛泽东、邓小平生平和传记', 1, 1); 
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('A8', '马克思主义、列宁主义、毛泽东思想、邓小平理论的学习和研究', 1, 1); 
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B-4', '哲学教育与普及', 2, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B0', '哲学理论', 2, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B1', '世界哲学', 2, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B2', '中国哲学', 2, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B3', '亚洲哲学', 2, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B4', '非洲哲学', 2, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B5', '欧洲哲学', 2, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B6', '大洋洲哲学', 2, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B7', '美洲哲学', 2, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B80', '思维科学', 2, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B81', '逻辑学（论理学）', 2, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B82', '伦理学（道德哲学）', 2, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B83', '美学', 2, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B84', '心理学', 2, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B9', '宗教', 2, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('C0', '社会科学理论与方法论', 3, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('C1', '社会科学现状及发展', 3, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('C2', '社会科学机构、团体、会议', 3, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('C3', '社会科学研究方法', 3, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('C4', '社会科学教育与普及', 3, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('C5', '社会科学丛书、文集、连续性出版物', 3, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('C6', '社会科学参考工具书', 3, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('C7', '社会科学文献检索工具书', 3, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('C8', '统计学', 3, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('C91', '社会学', 3, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('C92', '人口学', 3, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('C93', '管理学', 3, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('C94', '系统科学', 3, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('C95', '民族学', 3, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('C96', '人才学', 3, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('C97', '劳动科学', 3, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D0', '政治理论', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D1', '国际共产主义运动', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D2', '中国共产党', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D33', '亚洲各国共产党', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D34', '非洲各国共产党', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D35', '欧洲各国共产党', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D36', '大洋洲各国共产党', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D37', '美洲各国共产党', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D4', '工人、农民、青年、妇女运动与组织', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D5', '世界政治', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D6', '中国政治', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D73', '亚洲各国政治', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D74', '非洲各国政治', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D75', '欧洲各国政治', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D76', '大洋洲各国政治', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D77', '美洲各国政治', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D8', '外交、国际关系', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D9', '法律', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('DF', '法律', 4, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('E0', '军事理论', 5, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('E1', '世界军事', 5, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('E2', '中国军事', 5, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('E3', '亚洲各国军事', 5, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('E4', '非洲各国军事', 5, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('E5', '欧洲各国军事', 5, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('E6', '大洋洲各国军事', 5, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('E7', '美洲各国军事', 5, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('E8', '战略学、战役学、战术学', 5, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('E9', '军事技术', 5, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('E99', '军事地形学、军事地理学', 5, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F0', '经济学', 6, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F1', '世界各国经济概况、经济史、经济地理', 6, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F2', '经济计划与管理', 6, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F3', '农业经济', 6, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F4', '工业经济', 6, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F49', '信息产业经济（总论）', 6, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F5', '交通运输经济', 6, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F59', '旅游经济', 6, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F6', '邮电经济', 6, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F7', '贸易经济', 6, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F8', '财政、金融', 6, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('G0', '文化理论', 7, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('G1', '世界各国文化与文化事业', 7, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('G2', '信息与知识传播', 7, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('G3', '科学、科学研究', 7, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('G4', '教育', 7, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('G8', '体育', 7, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H0', '语言学', 8, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H1', '汉语', 8, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H2', '中国少数民族语言', 8, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H3', '常用外国语', 8, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H4', '汉藏语系', 8, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H5', '阿尔泰语系（突厥-蒙古-通古斯语系）', 8, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H61', '南亚语系（澳斯特罗-亚细亚语系）', 8, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H62', '南印语系（达罗毗荼语系、德拉维达语系）', 8, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H63', '南岛语系（马来亚-玻里尼西亚语系）', 8, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H64', '东北亚诸语言', 8, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H65', '高加索语系（伊比利亚-高加索语系）', 8, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H66', '乌拉尔语系（芬兰-乌戈尔语系）', 8, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H67', '闪-含语系（阿非罗-亚细亚语系）', 8, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H7', '印欧语系', 8, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H81', '非洲诸语言', 8, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H83', '美洲诸语言', 8, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H84', '大洋洲诸语言', 8, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H9', '国际辅助语', 8, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I0', '文学理论', 9, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I1', '世界文学', 9, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I2', '中国文学', 9, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I3', '亚洲各国文学', 9, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I4', '非洲各国文学', 9, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I5', '欧洲各国文学', 9, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I6', '大洋洲各国文学', 9, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I7', '美洲各国文学', 9, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('J0', '艺术理论', 10, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('J1', '世界各国艺术概况', 10, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('J2', '绘画', 10, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('J29', '书法、篆刻', 10, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('J3', '雕塑', 10, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('J4', '摄影艺术', 10, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('J5', '工艺美术', 10, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('J59', '建筑艺术', 10, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('J6', '音乐', 10, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('J7', '舞蹈', 10, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('J8', '戏剧艺术', 10, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('J9', '电影、电视艺术', 10, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K0', '史学理论', 11, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K1', '世界史', 11, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K2', '中国史', 11, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K3', '亚洲史', 11, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K4', '非洲史', 11, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K5', '欧洲史', 11, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K6', '大洋洲史', 11, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K7', '美洲史', 11, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K81', '传记', 11, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K85', '文物考古', 11, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K89', '风俗习惯', 11, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K9', '地理', 11, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('N0', '自然科学理论与方法论', 12, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('N1', '自然科学现状及发展', 12, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('N2', '自然科学机构、团体、会议', 12, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('N3', '自然科学研究方法', 12, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('N4', '自然科学教育与普及', 12, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('N5', '自然科学丛书、文集、连续性出版物', 12, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('N6', '自然科学参考工具书', 12, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('N7', '自然科学文献检索工具', 12, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('N8', '自然科学调查、考察', 12, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('N91', '自然研究、自然历史', 12, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('N93', '非线性科学', 12, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('N94', '系统科学', 12, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('N99', '情报学、情报工作', 12, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O1', '数学', 13, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O3', '力学', 13, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O4', '物理学', 13, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O6', '化学', 13, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O7', '晶体学', 13, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P1', '天文学', 14, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P2', '测绘学', 14, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P3', '地球物理学', 14, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P4', '大气科学（气象学）', 14, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P5', '地质学', 14, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P7', '海洋学', 14, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P9', '自然地理学', 14, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q-0', '生物科学的理论与方法', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q-1', '生物科学现状与发展', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q-3', '生物科学的研究方法与技术', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q-4', '生物科学教育与普及', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q-9', '生物资源调查', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q1', '普通生物学', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q2', '细胞生物学', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q3', '遗传学', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q4', '生理学', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q5', '生物化学', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q6', '生物物理学', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q7', '分子生物学', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q81', '生物工程学（生物技术）', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q89', '环境生物学', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q91', '古生物学', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q93', '微生物学', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q94', '植物学', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q95', '动物学', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q96', '昆虫学', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q98', '人类学', 15, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R-0', '一般理论', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R-1', '现状与发展', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R-3', '医学研究方法', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R1', '预防医学、卫生学', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R2', '中国医学', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R3', '基础医学', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R4', '临床医学', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R5', '内科学', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R6', '外科学', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R71', '妇产科学', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R72', '儿科学', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R73', '肿瘤学', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R74', '神经病学与精神病学', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R75', '皮肤病学与性病学', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R76', '耳鼻咽喉科学', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R77', '眼科学', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R78', '口腔科学', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R79', '外国民族医学', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R8', '特种医学', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R9', '药学', 16, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('S-0', '一般性理论', 17, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('S-1', '农业科学技术现状与发展', 17, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('S-3', '农业科学研究、试验', 17, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('S-9', '农业经济', 17, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('S1', '农业基础科学', 17, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('S2', '农业工程', 17, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('S3', '农学（农艺学）', 17, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('S4', '植物保护', 17, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('S5', '农作物', 17, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('S6', '园艺', 17, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('S7', '林业', 17, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('S8', '畜牧、动物医学、狩猎、蚕、蜂', 17, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('S9', '水产、渔业', 17, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('T-0', '工业技术理论', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('T-1', '工业技术现状与发展', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('T-2', '机构、团体、会议', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('T-6', '参考工具书', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('T-9', '工业经济', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TB', '一般工业技术', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TD', '矿业工程', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TE', '石油、天然气工业', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TF', '冶金工业', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TG', '金属学与金属工艺', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TH', '机械、仪表工业', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TJ', '武器工业', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TK', '能源与动力工程', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TL', '原子能技术', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TM', '电工技术', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN', '无线电电子学、电信技术', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TP', '自动化技术、计算机技术', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TQ', '化学工业', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TS', '轻工业、手工业', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TU', '建筑科学', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TV', '水利工程', 18, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('U-9', '交通运输经济', 19, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('U1', '综合运输', 19, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('U2', '铁路运输', 19, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('U4', '公路运输', 19, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('U6', '水路运输', 19, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('U8', '航空运输', 19, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('V1', '航空、航天技术的研究与探索', 20, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('V2', '航空', 20, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('V4', '航天（宇宙航行）', 20, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('V7', '航空、航天医学', 20, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('X-0', '环境科学理论', 21, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('X-1', '环境科学技术现状与发展', 21, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('X-4', '环境保护宣传教育及普及', 21, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('X-6', '环境保护参考工具书', 21, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('X1', '环境科学基础理论', 21, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('X2', '社会与环境', 21, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('X3', '环境保护管理', 21, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('X4', '灾害及其防治', 21, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('X5', '环境污染及其防治', 21, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('X7', '废物处理与综合利用', 21, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('X8', '环境质量评价与环境监测', 21, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('X9', '安全科学', 21, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Z1', '丛书', 22, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Z2', '百科全书、类书', 22, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Z3', '辞典', 22, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Z4', '论文集、全集、选集、杂著', 22, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Z5', '年鉴、年刊', 22, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Z6', '期刊、连续性出版物', 22, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Z8', '图书目录、文摘、索引', 22, 1);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('A11', '选集、文集', 23, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('A12', '单行著作', 23, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('A13', '书信集、日记、函电、谈话', 23, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('A14', '诗词', 23, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('A15', '手迹', 23, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('A16', '专题汇编', 23, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('A18', '语录', 23, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B0-0', '马克思主义哲学', 32, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B01', '哲学基本问题', 32, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B02', '辩证唯物主义', 32, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B03', '历史唯物主义（唯物史观）', 32, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('B08', '哲学流派及其研究', 32, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D2-0', '党的领导人著作', 64, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D20', '建党理论', 64, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D21', '党章', 64, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D22', '党的组织、会议及其文献', 64, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D23', '党史', 64, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D24', '党的总路线和总政策', 64, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D25', '党的领导', 64, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D26', '党的建设', 64, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D27', '中国共产党与各国共产党的关系', 64, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('D29', '中国共产主义青年团', 64, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F0-0', '马克思主义政治经济学（总论）', 92, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F01', '经济学基本问题', 92, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F02', '前资本主义社会生产方式', 92, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F03', '资本主义社会生产方式', 92, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F04', '社会主义社会生产方式', 92, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F05', '共产主义社会生产方式', 92, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F06', '经济学分支科学', 92, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F08', '各科经济学', 92, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('F09', '经济思想史', 92, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H1-0', '汉语理论与方法论', 110, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H102', '汉语的规范化、标准化、推广普通话', 110, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H109.2', '古代汉语', 110, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H109.3', '近代汉语', 110, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H109.4', '现代汉语', 110, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H11', '语音', 110, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H12', '文字学', 110, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H13', '语义、词汇、词义（训诂学）', 110, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H14', '语法', 110, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H15', '写作、修辞', 110, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H159', '翻译', 110, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H16', '字书、字典、词典', 110, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H17', '方言', 110, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('H19', '汉语教学', 110, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I200', '方针政策及其阐述', 129, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I206', '文学评论和研究', 129, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I207', '各体文学评论和研究', 129, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I209', '文学史、文学思想史', 129, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I21', '作品集', 129, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I22', '诗歌、韵文', 129, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I23', '戏剧文学', 129, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I239', '曲艺', 129, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I24', '小说', 129, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I25', '报告文学', 129, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I26', '散文', 129, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I269', '杂著', 129, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I27', '民间文学', 129, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I28', '儿童文学', 129, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I29', '少数民族文学', 129, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('I299', '宗教文学', 129, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K20', '通史', 149, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K21', '原始社会（约60万年前~4000多年前）', 149, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K22', '奴隶社会（约公元前21世纪~公元前475年）', 149, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K23', '封建社会（公元前475~公元1840年）', 149, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K25', '半殖民地、半封建社会（1840~1949年）', 149, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K27', '中华人民共和国时期（1949年~）', 149, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K28', '民族史志', 149, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('K29', '地方史志', 149, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O1-0', '数学理论', 172, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O1-6', '数学参考工具书', 172, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O1-8', '计算工具', 172, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O11', '古典数学', 172, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O119', '中国数学', 172, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O12', '初等数学', 172, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O13', '高等数学', 172, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O14', '数理逻辑、数学基础', 172, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O15', '代数、数论、组合理论', 172, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O17', '数学分析', 172, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O18', '几何、拓扑', 172, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O19', '动力系统理论', 172, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O21', '概率论与数理统计', 172, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O22', '运筹学', 172, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O23', '控制论、信息论（数学理论）', 172, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O24', '计算数学', 172, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('O29', '应用数学', 172, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P1-0', '理论与方法论', 177, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P1-2', '机构、团体、会议', 177, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P1-4', '教育与普及', 177, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P11', '天文观测设备与观测资料', 177, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P12', '天体测量学', 177, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P13', '天体力学（理论天文学）', 177, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P14', '天体物理学', 177, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P148', '天体化学', 177, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P149', '天体生物学', 177, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P15', '恒星天文学、星系天文学、宇宙学', 177, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P16', '射电天文学（无线电天文学）', 177, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P17', '空间天文学', 177, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P18', '太阳系', 177, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('P19', '时间、历法', 177, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q5-3', '生物化学研究法', 193, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q50', '一般性问题', 193, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q51', '蛋白质', 193, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q52', '核酸', 193, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q53', '糖（醣）', 193, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q54', '脂类', 193, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q55', '酶', 193, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q56', '维生素', 193, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q57', '激素', 193, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q58', '生物体其他化学成分', 193, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q591', '物质代谢及能量代谢', 193, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q592', '体液化学', 193, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q593', '器官生物化学', 193, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q594', '比较生物化学', 193, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('Q599', '应用生物化学', 193, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R51', '传染病', 211, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R52', '结核病', 211, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R53', '寄生虫病', 211, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R54', '心脏、血管（循环系）疾病', 211, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R55', '血液及淋巴系疾病', 211, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R56', '呼吸系及胸部疾病', 211, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R57', '消化系及腹部疾病', 211, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R58', '内分泌腺疾病及代谢病', 211, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R59', '全身性疾病', 211, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('R599', '地方病学', 211, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN-9', '电子工业经济', 252, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN0', '一般性问题', 252, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN1', '真空电子技术', 252, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN2', '光电子技术、激光技术', 252, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN3', '半导体技术', 252, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN4', '微电子学、集成电路（IC）', 252, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN6', '电子元件、组件', 252, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN7', '基本电子电路', 252, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN8', '无线电设备、电信设备', 252, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN91', '通信', 252, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN92', '无线通信', 252, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN93', '广播', 252, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN94', '电视', 252, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN95', '雷达', 252, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN96', '无线电导航', 252, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN97', '电子对抗（干扰及抗干扰）', 252, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN98', '无线电、电信测量技术及仪器', 252, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TN99', '无线电电子学的应用', 252, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TP-9', '自动化技术经济', 253, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TP1', '自动化基础理论', 253, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TP2', '自动化技术及设备', 253, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TP3', '计算技术、计算机技术', 253, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TP6', '射流技术（流控技术）', 253, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TP7', '遥感技术', 253, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('TP8', '远动技术', 253, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('V2-9', '航空运输经济', 265, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('V21', '基础理论及试验', 265, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('V22', '飞机构造与设计', 265, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('V23', '航空发动机（推进系统）', 265, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('V24', '航空仪表、航空设备、飞行控制与导航', 265, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('V25', '航空用材料', 265, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('V26', '航空制造工艺', 265, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('V27', '各类型航空器', 265, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('V31', '航空用燃料及润滑剂', 265, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('V32', '航空飞行术', 265, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('V35', '航空港（站）、机场及其技术管理', 265, 2);
INSERT INTO `category`(`cat_symbol`, `cat_name`, `cat_pid`, `cat_level`) VALUES ('V37', '航空系统工程', 265, 2);

-- ----------------------------
-- Records of lease
-- ----------------------------
INSERT INTO `lease`(`stu_id`, `book_id`, `lease_date`, `return_date`) VALUES (1, 18, '2020-06-28', '2020-07-03');
INSERT INTO `lease`(`stu_id`, `book_id`, `lease_date`, `return_date`) VALUES (7, 9, '2020-07-01', '2020-07-06');
INSERT INTO `lease`(`stu_id`, `book_id`, `lease_date`) VALUES (1, 1, '2020-07-02');
INSERT INTO `lease`(`stu_id`, `book_id`, `lease_date`) VALUES (3, 5, '2020-07-03');
INSERT INTO `lease`(`stu_id`, `book_id`, `lease_date`) VALUES (4, 1, '2020-07-03');
INSERT INTO `lease`(`stu_id`, `book_id`, `lease_date`, `return_date`) VALUES (6, 3, '2020-07-04', '2020-07-10');
INSERT INTO `lease`(`stu_id`, `book_id`, `lease_date`) VALUES (1, 7, '2020-07-04');
INSERT INTO `lease`(`stu_id`, `book_id`, `lease_date`) VALUES (8, 10, '2020-07-06');
INSERT INTO `lease`(`stu_id`, `book_id`, `lease_date`) VALUES (10, 10, '2020-07-07');
INSERT INTO `lease`(`stu_id`, `book_id`, `lease_date`) VALUES (9, 2, '2020-07-07');

-- ----------------------------
-- Records of student
-- ----------------------------
INSERT INTO `student`(`stu_num`, `stu_name`, `stu_sex`, `stu_age`, `stu_dept`) VALUES ('201823025188', '张三金', '男', 20, '计算机科学与技术');
INSERT INTO `student`(`stu_num`, `stu_name`, `stu_sex`, `stu_age`, `stu_dept`) VALUES ('201923024953', '李雪', '女', 19, '软件工程');
INSERT INTO `student`(`stu_num`, `stu_name`, `stu_sex`, `stu_age`, `stu_dept`) VALUES ('201741015090', '张木南', '男', 21, '计算机科学与技术');
INSERT INTO `student`(`stu_num`, `stu_name`, `stu_sex`, `stu_age`, `stu_dept`) VALUES ('201852025111', '黎九日', '男', 20, '计算机科学与技术');
INSERT INTO `student`(`stu_num`, `stu_name`, `stu_sex`, `stu_age`, `stu_dept`) VALUES ('201711013926', '赵日立', '女', 21, '电子信息工程');
INSERT INTO `student`(`stu_num`, `stu_name`, `stu_sex`, `stu_age`, `stu_dept`) VALUES ('201823025107', '张三木', '男', 20, '计算机科学与技术');
INSERT INTO `student`(`stu_num`, `stu_name`, `stu_sex`, `stu_age`, `stu_dept`) VALUES ('201623025027', '王水林', '男', 22, '计算机科学与技术');
INSERT INTO `student`(`stu_num`, `stu_name`, `stu_sex`, `stu_age`, `stu_dept`) VALUES ('201823025038', '刘士心', '男', 20, '计算机科学与技术');
INSERT INTO `student`(`stu_num`, `stu_name`, `stu_sex`, `stu_age`, `stu_dept`) VALUES ('201821075736', '周晨', '男', 20, '电子商务');
INSERT INTO `student`(`stu_num`, `stu_name`, `stu_sex`, `stu_age`, `stu_dept`) VALUES ('201932114396', '吴万虹', '女', 19, '软件工程');

-- ----------------------------
-- Records of sys_user
-- ----------------------------
INSERT INTO `sys_user`(`username`, `password`, `salt`, `email`, `phone`, `status`) VALUES ('admin', '8532695736a9f1287f0b07447ea1dafa', '39d1db4f13584d268adbf0a39ed07bb7', NULL, NULL, 1);
INSERT INTO `sys_user`(`username`, `password`, `salt`, `email`, `phone`, `status`) VALUES ('test1', 'c274a848da3782f1206cab06e39cc499', 'faa7cc58f20d4e2ab44b92d79c93322d', 'test1@sihenzhang.com', '13723456789', 0);
INSERT INTO `sys_user`(`username`, `password`, `salt`, `email`, `phone`, `status`) VALUES ('test2', '6a43151b7bceeba0a23d2c2ad0ac8dcb', 'a2453ca11ef740e09549fd5741258119', NULL, '15145678901', 1);
INSERT INTO `sys_user`(`username`, `password`, `salt`, `email`, `phone`, `status`) VALUES ('test3', '7ac40d21c9b53ab3c920e2961c3202b7', 'd72f7e18a94141a6a6c0b5a9f64fdfc4', 'test3@sihenzhang.com', NULL, 1);
INSERT INTO `sys_user`(`username`, `password`, `salt`, `email`, `phone`, `status`) VALUES ('test4', '2e7734ca30515f8034aff90709e2bf5d', '9d8142f2472741848ab34a966c4af077', 'test4@sihenzhang.com', '15012345678', 1);

SET FOREIGN_KEY_CHECKS = 1;
